### ISSUE TITLE
Make PDFs fully accessible

### ISSUE THREAD

**Issue by christoball** [TNRIS/site-mockup#100]
### An sample of process from Matt Erickson run aerometric.pdf

I’ve made this document to be fully accessible.  These steps are on the top of text-recognition:
 
1. Convert scanned image in each page into artifact
    1. Tools >> Content >> Edit Object
    2. Use cursor to click on the empty space of the page
    3. Right-click to open context menu and select Create Artifact…
    4. Click OK on the Create Artifact dialog, by default, it selected Page as artifact type.
    5. Repeat on all pages
2. Set up Tags (warning: this is a lot of work)
  1. Tools >> Accessibility >> TouchUp Reading Order
  2. Start with first page, first line (first set).  In aerometric_temp.pdf document, I started by selecting “Contract No. CCG-GIS-2008-001”
  3. Right-click on the highlighted text to open the context menu, select “Tag as text”
  4. Next set is the document title “CONTRACT Between…Data Sets (HPIDS)”, select all of this and on the context menu, select “Tag as header 1”
  5. Next set is the body, select all of the text from the title to beginning of the “Article I. Introduction” (don’t include “Article I. Introduction” in your selection), select “Tag as text”
  6. Next set is the header “Article I. Introduction” and select “Tag as header 2”
  7. Next set is the body after header 2 and tag as text
  8. On 2nd page and on except for the last page, do the same, but only use header 2 or text as tags in order and make sure that the pagination is not part of the text body, but a separate text in the latest order of this page.
  9. On the last page, I’ve assigned signatures as a figure with alt text and gave them with an appropriate alt text – you can see how I did it.
3. Sometimes, for some weird reasons, after you perform a Full Check, it would probably inform you that there are XX number of figures with no alt text and if you click on the link, it will not go anywhere.  Go to Tag tree and you’ll see a bunch of “Figure” tags in the beginning of the tag tree, go ahead and delete them (and no, you can’t just group delete them, and you have to delete one by one).

**Comment by wilsaj** [comment]
Closing - links have been pulled from HPIDS page
