### ISSUE TITLE
HPIDS page changes

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/site-mockup#101]
From Gayla:

- Ryan told me about the accessibility issue with all the pdfs linked on this page. Can we pull all those and link to the master contract from CCG’s website here: http://www.ccg.state.tx.us/documents/GISBaseContract.pdf
 
- Datasets needs to be Data Sets on the title and first paragraph. High Priority Imagery and Data Sets is the official name of the contract.
 
- Sanborn and GeoComm are missing from Approved Vendors.

- Also, we need a Quantum Spatial box. They don’t technically have a master contract to link to but are covered by the Aero-metric and PhotoScience contracts. They are now answering RFPs as Quantum Spatial so I think they deserve their logo here.

**Comment by christoball** [comment]
Ive added the logos and made those changed, i made an issue #106  that I closed since i hadnt seen this yet

I've gone ahead and changed the page name to high-priority-imagery-data-sets for consistency, and I've fixed all the broken links that resulted from that change

Good on everything else
