### ISSUE TITLE
data catalog looks funny

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/site-mockup#110]
happened in: 9e488ae7bec174c88e605d5c7f135a71d17783ea

looks like:
![screen shot 2015-01-10 at 9 46 24 am](https://cloud.githubusercontent.com/assets/303866/5692130/b0ed3500-98ad-11e4-9f67-10c0e20d67f2.png)

**Comment by christoball** [comment]
Made some adjustments and it's looking good now.
