### ISSUE TITLE
accessibility: PDFs need to have language attribute set

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/site-mockup#95]
From Matt:

> Many PDFs need to be have the language attribute set to English – CTRL+D or File >> Document Properties to open the dialog box and select Advanced tab.  In that tab, under Reading Options, change Language to English.

**Comment by christoball** [comment]
Is this for the vendor contracts?

I checked them and they all show the language as English.

**Comment by wilsaj** [comment]
This was Matt's recommendation from the accessibility audit. Can you discuss it with him?

**Comment by christoball** [comment]
Set language to English, will make fully accessible soon after launch.
