### ISSUE TITLE
individual training page urls need to be unique

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/site-mockup#96]
We can't just use class title alone, because classes can be repeated. For example, there are two "Fundamentals of ArcGIS" courses currently in the training CSV at different times of the year so `/training/fundamentals-of-arcgis/` is ambiguous. Using the url_date field as well as class_title avoids this by giving them each a unique url: `/training/fundamentals-of-arcgis/april-2015/` and `/training/fundamentals-of-arcgis/august-2015/` so the pages can display the event information for each course.

@christoball - any reason not to do this?

**Comment by christoball** [comment]
No reason not to - is this a good reason why we should just make each training course it's own markdown. It would make it easier to parse out the url using the date, right?
